### ISSUE TITLE
Remove restrictions on `isize` and `usize`

### ISSUE THREAD

**Issue by BartMassey** [kas-gui/easy-cast#3]
It seems possible to make this crate work for 16-bit and 128-bit `isize` with a little more work. I can try to throw together a PR if desired.

I *believe* that Rust always requires `size_of::<isize>() == size_of::<usize>()`, and am pretty sure that all implementations assume that anyhow. I don't have chapter and verse on that, though.

**Comment by dhardy** [comment]
Already working on this actually (just hit [this](https://internals.rust-lang.org/t/int-ty-is-signed/14298) with my generic test method).

**Comment by BartMassey** [comment]
Closed by PR #6. Thanks much!
