### ISSUE TITLE
Provide `TryConv` and `TryCast`

### ISSUE THREAD

**Issue by BartMassey** [kas-gui/easy-cast#4]
Would be nice to provide a way to handle cast errors.

This is especially important since `std::convert::TryInto()` currently doesn't support conversions from integer to floating types for some reason: it would be nice to have conversions that fail if inexact.

**Comment by dhardy** [comment]
We could add `try_conv` / `try_cast` methods. I'm not sure how much code share there will be with the `conv`/`cast` variants; better to look at the error messages first.

BTW if someone would like to contribute a decent test suite that would help a lot.

**Comment by BartMassey** [comment]
Thank you!
