### ISSUE TITLE
Document MSRV

### ISSUE THREAD

**Issue by vks** [kas-gui/easy-cast#9]
Is there a minimal supported Rust version for this crate? It seems to require associated constants, which makes it incompatible with older Rust versions.

**Comment by dhardy** [comment]
I pulled the code from KAS for which the MSRV is "the latest release", but we should probably be a bit more careful here.

**Comment by vks** [comment]
Sure, that's fair! It would be nice to document this somewhere.

I used `easy-cast` to get rid of my dependency on the unmaintained `conv` crate in `average`, which worked well but turned out to be incompatible with Rust 1.36. (the MSRV of Rand).

**Comment by dhardy** [comment]
Why does it require associated consts? For `LBOUND`/`UBOUND`? If so they could just be moved to the lib root.

I'll try testing later if you like but slow internet makes it a pain to install various Rustc versions.

**Comment by vks** [comment]
This is the error:

```
error[E0599]: no associated item named `MIN` found for type `i8` in the current scope
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/easy-cast-0.2.0/src/lib.rs:319:46
    |
319 |                     const LBOUND: $x = <$y>::MIN as $x;
    |                                              ^^^ associated item not found in `i8`
...
353 | impl_float!(f32: i8, i16, i32, i64, i128, isize);
    | ------------------------------------------------- in this macro invocation
```

So I think it is about using the associated constant in `std`, which is not available in old Rust versions. Should be easy to fix (by importing the module), but I don't know whether you want to bother to support such old Rust versions.

**Comment by dhardy** [comment]
So minimum viable version is probably 1.43.0, eleven months old. 1.36.0 is approx twenty months old; from discussions I remember hardly anyone cares beyond about six months. It seems silly bumping the rand version for this though, so I'm happy to support older rustc here (probably requires `$t: tt` or similar in the macro to make `std::$t::MIN` work).

**Comment by dhardy** [comment]
I think supporting older Rustc is easy enough, but there may be another problem with using this in rand: we expect `no_std` to work.

This crate doesn't use any trig/exponential float ops, but does use `ceil`, `floor` and `round`, and it seems *those* are not supported in `core`.

**Comment by dhardy** [comment]
> I used easy-cast to get rid of my dependency on the unmaintained conv crate in average, which worked well but turned out to be incompatible with Rust 1.36. (the MSRV of Rand).

But `average` is only used as a dev-depenendency in `rand_distr`, so why do we care about Rust 1.36?

**Comment by vks** [comment]
Don't we run the tests on 1.36 too?

**Comment by dhardy** [comment]
CI for 1.36.0 is done.
